[pytest]
testpaths = tests
addopts = -v --tb=short
filterwarnings =
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
    ignore:GPU available but not used.*:UserWarning:pytorch_lightning.trainer.setup
    ignore:`isinstance\(treespec, LeafSpec\)` is deprecated.*
    ignore:The 'train_dataloader' does not have many workers.*:UserWarning:pytorch_lightning.trainer.connectors.data_connector
    ignore:Could not find the number of physical cores.*:UserWarning:joblib.externals.loky.backend.context
